@startuml
title Диаграмма контекста (эко-)системы SmartHome

top to bottom direction

!include C4_Context.puml

Person(User, "Пользователь", "Пользователь (эко-)системы SmartHouse")
Person(Admin, "Администратор", "Администратор системы")
Person(Support, "Специалист поддержки*", "Специалист команды службы поддержки")
Person(Marketing, "Специалист по продажам и маркетингу*", "Специалист команды по продажам и маркетингу")

System(SmartHome, "(Эко-)Система SmartHome", "Система SmartHome")

System_Ext(SmartDevices, "Умные устройства", "Датчики и исполнительные механизмы, поддерживающие работу с системой")
System_Ext(PaymentService, "Внешний платежный сервис*", "Сервис организации-партнера для проведения финансовых транзакций")
System_Ext(EMailService, "Внешний сервис для взаимодействия с пользователями через EMail*", "Внешний сервис для взаимодействия с пользователями через EMail (Google/Yandex/Mail и т.д.)")
System_Ext(OAuthProvider, "Внешний сервис для аутентификации*", "Сервис для аутентификации пользователей через внешние системы (Google/Yandex/Mail и т.д.)")

Rel(User, SmartHome, "Использует систему: управляет устройствами, просматривает данные мониторинга, программирует сценарии использования*, подключает новые комплекты*, регистрируется в системе*, оплачивает услуги*")
Rel(Admin, SmartHome, "Поддерживает работоспособность системы, в текущей реализации также в ручном режиме выполняет добавление новых пользователей и их устройств")
Rel(Support, SmartHome, "Осуществляет поддержку пользователей")
Rel(Marketing, SmartHome, "Управляет доступными для покупки устройствами, тарифами, анализирует продажи и т.д.")

Rel(SmartHome, SmartDevices, "Управляет устройствами, собирает данные с датчиков (в случае опроса со стороны сервера)")
Rel(SmartDevices, SmartHome, "Отправляют данные (в случае периодической отправки на сервер)")
Rel(SmartHome, PaymentService, "Инициирует, подтвержает и запрашивает статус платежных операций")
Rel(SmartHome, EMailService, "Отправляет EMail'ы")
Rel(SmartHome, OAuthProvider, "Запрашивает данные для аутентификации")
Rel(EMailService, User, "Отправляет EMail'ы")

@enduml